### PR TITLE
Add Table break tag

### PR DESCRIPTION
**Pull request by pestOO**
Added information about using breaks in tables.

Related issue(s):APPLINK-26096, APPLINK-26661

### CODE REVIEW

**Comment by pestOO** [comment]
@joeygrover, please review

**Comment by ssmereka** [comment]
Thanks @pestOO :)

# Test

Tested and HTML `<br>` tag is supported in tables.

## Markdown

```
| test | test | test | test | This is <br> a test of a long sentence broken up into pieces using a br tag instead of wrapping the content like you might normally want or expect.  <br><br> It's really just using html tags, not sure if it needs to be documented, but someone make a pull-request to document it so let's just see if it works first anyways. |
```

## Result

smartdevicelink_-_documentation

# Discussion?

However, most HTML tags are supported because markdown is used to generate HTML.  Not sure if we want to get in the habit of documenting standard HTML unless it has unexpected behavior or something docdown specific.  

Any thoughts?

**Comment by pestOO** [comment]
@ssmereka 
With my SAD cases - long text in tables are common situation. And such functionality is really helpful.
But I could not provide you any risks related to this feature.

**Comment by ssmereka** [comment]
We have decided not to document HTML tags because their use should actually be avoided if at all possible.  It should be the templates job (not DocDown) to handle styling.  Using simple tags like `< /br>` shouldn't be a problem, but may have different affects on different templates based on the CSS/HTML/Javascript being used.  We have added a brief section about [HTML tags](https://github.com/smartdevicelink/sdl_markdown_spec#html).  Do you have any further input on the issue before I close this request?

**Comment by pestOO** [comment]
@ssmereka,
Thanks for information. You can close PR.
Am I right that `br` is still possible to use but will be redundant with next Portal changes due to auto-breaking table content?

**Comment by ssmereka** [comment]
@pest00 
Yes, you can use the `</br>` tag.  No it will not be redundant in the next Portal changes.

We will look into a better way to handle large amounts of text in a tables for the portal's template.

**Pull request closed without merging**
